### ISSUE TITLE
MMM code review

### ISSUE THREAD

**Issue by dirmeier** [wtraylor/modular_megafauna_model#52]
Ciao Wolfgang,

the code/documentation/unit tests/etc etc are excellent and you've put significant work into it, so every review on this would feel a bit pedantic to me.

I'd like to ask you, however, to
-  add the example building/usage into README.md such that one doesn't have to go through the html docs,
- add CMAKE as dependency,
- add "add C++11 compatible compiler" as dependency.

Cheers, S

**Comment by wtraylor** [comment]
@dirmeier Thank you for the suggestions. I have moved the Quickstart Guide to the README and have mentioned the dependencies in the README, too. You can see it in the [develop branch](https://github.com/wtraylor/modular_megafauna_model/tree/develop).

Let me know what you think.

**Comment by dirmeier** [comment]
Great! Looks really like a nice tool. Thank you for the updates
