### ISSUE TITLE
Unit tests failed

### ISSUE THREAD

**Issue by WTejler** [wtraylor/modular_megafauna_model#54]
Hi! 
When I try to run make megafauna_unit_test it runs but I get the following error message: 
Error: No viable overloaded '=' 
I am on a mac using AppleClang 14.03. 

Since last time I now tried running it with GCC (version 13) instead, still same error message

**Comment by wtraylor** [comment]
Great that you could fix the issue! What did you do to fix it?

**Comment by WTejler** [comment]
I thought that I had made sure that I was using GCC as default compiler, however for som reason CMake was still going back to using AppleClang. So what I had to do was to go into the CMake compiler settings (through the terminal) and manually change the compiler to GCC.
