### ISSUE TITLE
Unrecognized instruction mnemonic for Mac. 

### ISSUE THREAD

**Issue by WTejler** [wtraylor/modular_megafauna_model#55]
I managed to fix the previous error, but now when I run the unit tests on my Mac, I get a new error. 
error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not? The error appears to be happening in catch_main.cpp.o    
<img width="1193" alt="Skärmavbild 2023-10-19 kl  14 59 17" src="https://github.com/wtraylor/modular_megafauna_model/assets/146729558/2c170e3b-bbaf-42c8-989b-7a9a81812cb5">

**Comment by wtraylor** [comment]
[Instruction mnemonics](https://encyclopedia2.thefreedictionary.com/instruction+mnemonic) are for assembler language. Are you compiling on an ARM processor? (That is, a mobile device such as a tablet or phone?)
Perhaps it relates to [this upstream bugfix](https://github.com/catchorg/Catch2/commit/a25c1a24af8bffd35727a888a307ff0280cf9387) in the Catch2 framework. It looks like I’d just need to update Catch2 to fix it. (It’s the framework for unit testing.)

**Comment by WTejler** [comment]
Yes I am pretty sure that my Macbook pro laptop 2023 (which is what I am using to compile this) is using an ARM processor. Thank you very much for your help.

**Comment by wtraylor** [comment]
I updated the Catch test framework. Could you please try it with the new release version?

**Comment by WTejler** [comment]
Yes, everything works now! 
Thanks!

**Comment by wtraylor** [comment]
Fixed by 58b64ee49022aae6fe5d074c90f6e043d18ca161
